### ISSUE TITLE
Use .png or .svg format for icon instead of .ico

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink-chocolatey#19]

**Comment by gravyboat** [comment]
There should probably be a duplicate issue on the main repo for discussion of this

**Comment by Conjuro** [comment]
streamlink/streamlink#2165

Guessing it will be in the next release.

The SVG file (/icon.svg in above linked PR) would be preferred. If we for whatever reason go with one of the raster images instead, it should be PNG, minimum 128x128 and not too large, so the 256x256 image should be good.
