### ISSUE TITLE
Streamlink 0.10.0 not working ?

### ISSUE THREAD

**Issue by Caf** [streamlink/streamlink-chocolatey#24]
I guet errors with the upgrade, uninstalling it and reinstalling 0.9 fix the problem. Did I miss something?

Launching Streamlink with or without args gives me that =

File "C:\Users\caf\AppData\Local\Streamlink\bin\streamlink-script.py", line 14, in <module>
from streamlink_cli.main import main
File "C:\Users\caf\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 18, in <module>
from streamlink.plugins.twitch import TWITCH_CLIENT_ID
ImportError: No module named 'streamlink.plugins.twitch'

Thanks for the help!

**Comment by scowalt** [comment]
Hmmm, I'm not running into the same issue upgrading from v0.9.0 to v0.10.0.

Just to confirm, you installed streamlink through chocolatey and upgraded through `choco upgrade`?

**Comment by Caf** [comment]
I did, but since I was the only one with problems apparently, I RE-did everything (uninstall / reinstall / cleaning leftovers from other installations and it finally worked (did it 3 times this week-end, why it didn't work at the 1st reinstall is a mystery... :/ )

Sorry for the false alert and thx for the answer!

**Comment by scowalt** [comment]
Thanks for following-up! Glad your install is working now.
