### ISSUE TITLE
Update chocolatey package to v0.2.0

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink-chocolatey#4]
This is blocked by https://github.com/streamlink/streamlink/issues/312

**Comment by gravyboat** [comment]
@scowalt Right now the main installer still seems to be broken so you might not want to build yet.

**Comment by scowalt** [comment]
Thanks for the heads-up! Updating main post

**Comment by gravyboat** [comment]
@scowalt This is fixed, should be set to go.
