### ISSUE TITLE
New automated job doesn't commit code back to repository

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink-chocolatey#69]
![image](https://user-images.githubusercontent.com/1100550/155921174-cac905e8-c030-42cb-b3b4-e385f6df3d5a.png)

I can't enable this in the repo settings

So when my new job goes to commit its changes back to the repo, it fails

![image](https://user-images.githubusercontent.com/1100550/155921207-17e3718f-74bd-4e52-a72e-a5cd6c801896.png)

@bastimeyer , would it be possible to have that setting enabled on this repository?

**Comment by scowalt** [comment]
Doing the same on https://github.com/streamlink/streamlink-twitch-gui-chocolatey would be great too

**Comment by gravyboat** [comment]
@scowalt You have admin access which are the same permissions I have. By default for the org itself we have `Read repository contents permission `. I can change it for the whole org, but I can't modify it for this specific repository for some reason. The docs note the following:

> You can set the default permissions for the GITHUB_TOKEN in the settings for your organization or your repositories. If you choose the restricted option as the default in your organization settings, the same option is auto-selected in the settings for repositories within your organization, and the permissive option is disabled.

@bastimeyer Any concerns over enabling this at an org level so we can get this integration issue resolved?

**Comment by scowalt** [comment]
It looks like I could work around this by generating a custom `GITHUB_TOKEN` that has write permissions to the repository, and using that instead of the default one.

That solution is far less elegant and is also flaky. (What if the token expires?). Hopefully we can just change this setting

**Comment by bastimeyer** [comment]
Any kind of write permissions must be explicitly enabled in the workflow file for the according job/step via the `permissions` field. Please see the github actions docs. It should **not** be enabled at orga level, or even repo level.

Btw, I don't agree with the automated package publishing, as I pointed out [here](https://github.com/streamlink/streamlink/pull/4356#issuecomment-1046074812) and [here](https://github.com/streamlink/streamlink/pull/4356#issuecomment-1046929191). Packaging should not be done automatically. You're basically replacing an automated event that you were proposing earlier with a daily cronjob that's polling the streamlink repo for its releases.

What I said in the other PR was that a package should be built and deployed when a tag gets pushed to the package repo, after the new source (tag or commit) was reviewed.

Even if chocolatey is just a wrapper for executing installers, it's still the responsibility of a packager to validate and check for any kind of dependency issues, etc.

**Comment by scowalt** [comment]
> Any kind of write permissions must be explicitly enabled in the workflow file for the according job/step via the permissions field. Please see the github actions docs. It should not be enabled at orga level, or even repo level.

Got it. I can investigate this later. It "just worked" in my local test repo, so I assumed it was a repo configuration, but maybe I can explicitly add extra permissions in the `yml`.

I totally understand your perspective on not wanting to automate packages. Both @Conjuro and I have been pretty inactive lately, and many users were concerned that the packages were out-of-date.

I won't be able to keep up with this chore in the long term, especially with the number of packages that I maintain. The only way to keep the chore sustainable for me, personally, is to automate it. This allows for more immediate package updates for users, and takes "less" of my time (though there is the up-front cost of writing the automation). Writing automation is also more interesting to me than manually generating hashes, running through install steps, etc.

Ideally there would be a human doing all of this, but having it automated is still probably better than not having it done at all.

**Comment by scowalt** [comment]
Resolved the original issue with this bit of code:

```yml
permissions:
  # Required for add-and-commit
  contents: write
  ```
