### ISSUE TITLE
Streamlink Windows installer builds have been moved to streamlink/windows-installer

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-chocolatey#70]
@scowalt, the Streamlink Windows installer builds have been moved to streamlink/windows-installer, which means the chocolatey package build/publish config is not going to work with the next Streamlink release.

- https://github.com/streamlink/streamlink/pull/4405
- https://github.com/streamlink/windows-installer

**Comment by scowalt** [comment]
Thanks for the heads-up! I'll take a look when I get the chance

**Comment by bastimeyer** [comment]
- https://github.com/streamlink/streamlink/releases/tag/4.0.0
- https://github.com/streamlink/windows-installer/releases/tag/4.0.0-1

> BREAKING/packaging: replaced Windows installers with new ones built at [streamlink/windows-installer](https://github.com/streamlink/windows-installer)

**Comment by scowalt** [comment]
Nuget doesn't support the `4.0.0-1` syntax 🙁 . It's valid semver, but maybe Nuget doesn't support semver?

I have to mess with the version string to get this to work. Just an FYI
