### ISSUE TITLE
Update to Streamlink 4.2.0

### ISSUE THREAD

**Issue by SAJewers** [streamlink/streamlink-chocolatey#71]
https://github.com/streamlink/streamlink/releases/tag/4.2.0

**Comment by scowalt** [comment]
Thanks for the report and for your patience. I finally had a chance to iterate on this today. A new package should be uploaded today or tomorrow

**Comment by scowalt** [comment]
I expect this to work, lmk if there are issues! https://community.chocolatey.org/packages/streamlink/4.2.0.2
