### ISSUE TITLE
choco push of 6.0.0-1 failed

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-chocolatey#74]
See https://github.com/streamlink/streamlink-chocolatey/actions/runs/5618587287/job/15224405193

Please also have a look at the built package, because the installer has received some changes with the addition of another page, and I don't know how this affects the `/S` argument. Ideally, the package shouldn't use the installer at all and should be based on the zip archive. The only difference is the lack of the config file and thus the missing `--ffmpeg-ffmpeg` CLI arg by default.

The scoop package [does the correct thing](https://github.com/ScoopInstaller/Extras/blob/29aa68a63180c8a109e98302e45a823d6866405e/bucket/streamlink.json#L37) and builds a wrapper executable which sets the `--ffmpeg-ffmpeg` CLI argument to the path of the bundled ffmpeg executable which the installer would do otherwise automatically.

Thanks.

**Comment by scowalt** [comment]
The push failure is on my radar. Chocolatey v1.0 changed how to push packages. I updated this in some of my other repos but not this one.

I can try out the installed package locally too to make sure the package works out of the box

**Comment by scowalt** [comment]
The fix will look like this https://github.com/scowalt/chocolatey-packages/commit/7b10ae90787333666bdfe189ddd1a99216fd46c0

**Comment by scowalt** [comment]
Fixed repo. Tested a fresh install of 6.0.0-1 and it works well.

I'll open a new task to make a portable version of the package (that installs from the zip archive)
