### ISSUE TITLE
Update to 0.4.0

### ISSUE THREAD

**Issue by jarlave** [streamlink/streamlink-chocolatey#8]
Hi, me again, can you please update to 0.4.0?

**Comment by scowalt** [comment]
Thanks for the ping, I'll get to it this weekend!

**Comment by gravyboat** [comment]
@jarlave Just as a heads up I edited your title and comment to note that it's `0.4.0` instead of `4.0` in case anyone stumbles on this in the future so we can avoid confusion.

**Comment by jarlave** [comment]
@gravyboat oh, thanks, I notice I've made the same mistake last time too, I'll try to make it right next time :D

**Comment by gravyboat** [comment]
@jarlave No worries, I'm not trying to give you a hard time! I just didn't want to modify your topic/comment without notifying you.
